[gcp_service_account]
type = "service_account"
project_id = "presenca-espaco-infantil"
private_key_id = "2b6da1e1316dcb93530ecf73834580a848466e34"
private_key = "-----BEGIN PRIVATE KEY-----\\nMIIEvQIBADANBgkq...SEU_FINAL=\\n-----END PRIVATE KEY-----\\n"
client_email = "streamlit-presenca@presenca-espaco-infantil.iam.gserviceaccount.com"
client_id = "102132964166847116681"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/streamlit-presenca%40presenca-espaco-infantil.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
